org: aluribalakalki
service: attendance-portal

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: dev
  environment:
    MONGODB_URL: ${env:MONGODB_URL}
    
functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          allowCredentials: true


plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 8000
